### PR TITLE
DRAFT: Refined pulse region

### PR DESCRIPTION
**Pull request by abougouffa**
Discussion at #22

### CODE REVIEW

**Comment by protesilaos** [comment]
Thank you @abougouffa! Since you are also touching the window-related parts, do you want to set `pulsar-pulse-on-window-change` as we discussed?

Also, I am a bit confused with the commit authors here and the "2 participants" that GitHub shows me. Is your branch building on top of @shipmints? Anyway, my point is to reach consensus with what we are doing.

**Comment by shipmints** [comment]
If it's okay with everyone, I'll coordinate this round of changes in my branch. That's what I've been doing.

**Comment by abougouffa** [comment]
Thank you for the review @protesilaos.

Yes, I've pushed my commits on top of @shipmints's branch.

@shipmints I think you should pull from my branch and push your changes on top of it instead of copy-pasting the code to your branch! This keeps the authorship of the different parts.

**Comment by shipmints** [comment]
I'll do that next time. You'll be mentioned in the code and the docs no problem. It was too much extra work for me for the few changes on top of the ones I already had in place and ready to be tested for feedback (Emacs workflow tends to be commentary and/or patches not pushes). Better for collab of this scale to be consolidated. If you have a github recipe that makes that operation easy for me in the future, let me know.

**Comment by abougouffa** [comment]
@shipmints [`forge`](https://github.com/magit/forge) does that perfectly. You can easily track PRs and pull from other upstream repos with a few keystrokes!

**Comment by abougouffa** [comment]
You're welcome!

> Good to know but that's not a recipe and I've never used it.
I don't know what you mean by a recipe, but anyway, it is a good package to have, especially if you use `magit`. Then, the workflow is pretty straightforward, for each local Git repo you can track the remote repo on the Github/Gitlab/Bitbucket/... server. Fetch the PRs (you can locally checkout the branch of another contributor, merge locally, and push to the server)... and so on.

I use it to maintain my personal private/open source projects on Github/Gitlab, and I used in work with Gitlab.. It make thinks easier

Thank you for your involvement!

> I might put a comment in the code to thank minad also. He's a wonderful Emacs contributor overall.

Yep, I did the changes very quickly when I was in the train, I pushed before loosing internet connection. I was thinking of adding a comment to give credits to minad, something like:

```elisp
;; The logic of this feature is heavly inspired by minad's `goggles` package
(defun pulsar--after-change-pulse (beg end len)
 ....
```

This comment is also written in forge from Emacs!

**Comment by shipmints** [comment]
C'est bon. I'll "copy/paste"!:) that comment in now.

**Comment by abougouffa** [comment]
Merci @shipmints !

**Comment by protesilaos** [comment]
Let me know when you are ready to merge this.

**Comment by abougouffa** [comment]
@protesilaos Nop, not this PR. I will close it. @shipmints have taken these commits with some extra tweaks [in his branch](https://github.com/shipmints/pulsar/tree/region-window-change-redux). He needs to open another PR.

**Pull request closed without merging**
